name: Publish to maven central
on:
  push:
    tags:
      - release.**
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_KEY_ID }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.6.1
      - name: build and deploy
        run: mvn deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
