name: Publish to maven central
on:
  push:
    tags:
      - release.**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.6.1
      - name: build and deploy
        run: mvn install deploy -Dgpg.passphrase=${{ secrets.GPG_PASSWORD }}
